### ISSUE TITLE
Broken for Play >= 2.4

### ISSUE THREAD

**Issue by janlisse** [mandubian/play-json-zipper#12]
Hello,

i just tried to use your Zipper with Latest Play 2.4.1. It gives me:
```
 java.lang.NoSuchMethodError: play.api.libs.json.JsObject.<init>(Lscala/collection/Seq;)V
[info]   at play.api.libs.json.JsZipper$.mergeSiblingsAsObjLeft(JsZipper.scala:771)
[info]   at play.api.libs.json.JsZipper$.reify(JsZipper.scala:797)
[info]   at play.api.libs.json.JsZipper$class.up(JsZipper.scala:100)
[info]   at play.api.libs.json.JsZipper$$anon$1.up(JsZipper.scala:760)
[info]   at play.api.libs.json.JsZipper$class.root(JsZipper.scala:124)
[info]   at play.api.libs.json.JsZipper$$anon$1.root(JsZipper.scala:760)
[info]   at play.api.libs.json.JsZipper$class.createOrUpdatePath(JsZipper.scala:610)
[info]   at play.api.libs.json.JsZipper$$anon$2.createOrUpdatePath(JsZipper.scala:749)
```

My code:
```scala
val zipper = JsZipper(Json.parse("""{"foo":"bar"}""")
    val withCat = zipper.createOrUpdatePath(__.\("categories"), {
      _ match {
        case arr: JsArray => arr :+ JsString("1")
        case _ => Json.arr("1")
      }
    })
```

**Comment by ScalaWilliam** [comment]
+1

**Comment by CodeCraftStudio** [comment]
+1

**Comment by andrekampert** [comment]
Created pull request https://github.com/mandubian/play-json-zipper/pull/14

**Comment by JakubKahovec** [comment]
+1

**Comment by jgonian** [comment]
+1

**Comment by andrekampert** [comment]
I've made the fix for Play 2.4 available on [BinTray](https://bintray.com/productfoundry/maven/play-json-zipper/view#files/com/productfoundry/play-json-zipper_2.11/1.3). Feel free to use this version until the pull request gets merged into the main project.

To add the SBT dependency, you need to add our repository:

```sbt
resolvers ++= Seq(
  "productfoundry at bintray" at "http://dl.bintray.com/productfoundry/maven"
)
```

Add the SBT dependency

```sbt
libraryDependencies += "com.productfoundry" %% "play-json-zipper" % "1.3"
```

**Comment by JakubKahovec** [comment]
Thank you

**Comment by dgouyette** [comment]
+1

**Comment by kamran-m** [comment]
+1

**Comment by lielran** [comment]
+1
